# Generated by Django 3.0.3 on 2023-12-04 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioDevolutivo',
            fields=[
                ('fecha_Registro', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField()),
                ('serial', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('factura', models.ImageField(blank=True, null=True, upload_to='facturaElemento/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosInventarioConsumible',
            fields=[
                ('nombreElemento', models.CharField(max_length=25)),
                ('categoriaElemento', models.CharField(choices=[('Devolutivo', 'Devolutivo'), ('Consumible', 'Consumible')], max_length=25)),
                ('estadoElemento', models.CharField(choices=[('Garantia', 'Garantia'), ('Baja', 'Baja'), ('Disponible', 'Disponible'), ('Prestamo', 'Prestamo')], default='Disponible', max_length=25)),
                ('descripcionElemento', models.CharField(max_length=25)),
                ('costoUnidadElemento', models.IntegerField()),
                ('disponible', models.IntegerField(default=0)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosInventarioDevolutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('categoria', models.CharField(choices=[('D', 'Devolutivo'), ('C', 'Consumible')], default='C', max_length=25)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Garantia', 'Garantia'), ('Baja', 'Baja'), ('Prestamo', 'Prestamo')], default='D', max_length=25)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor_unidad', models.IntegerField()),
                ('disponibles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosSena',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('tipoIdentificacion', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('TI', 'Tarjeta de identidad'), ('PEP', 'Permiso especial de permanencia'), ('O', 'Otro')], default='CC', max_length=25)),
                ('numeroIdentificacion', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=35)),
                ('celular', models.CharField(max_length=10)),
                ('rol', models.CharField(choices=[('superAdmin', 'super Administrador'), ('I', 'instructor'), ('M', 'Monitor')], default='I', max_length=25)),
                ('cuentadante', models.CharField(choices=[('superAdmin', 'Super Admin'), ('adminS', 'administrador Solidario'), ('adminD', 'administrador Directo'), ('monitor', 'monitor')], default='adminD', max_length=25)),
                ('tipoContrato', models.CharField(choices=[('Planta', 'P'), ('Contratista', 'C'), ('Aprendiz', 'A')], default='P', max_length=25)),
                ('is_active', models.BooleanField(default=1)),
                ('duracionContrato', models.CharField(max_length=25)),
                ('password', models.CharField(default='', max_length=100)),
                ('recovery_token', models.CharField(blank=True, max_length=30, null=True)),
                ('fotoUsuario', models.ImageField(blank=True, null=True, upload_to='usuarioFoto/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrega', models.DateField()),
                ('fechaDevolucion', models.DateField()),
                ('estado_actualizado', models.BooleanField(default=False)),
                ('estadoPrestamo', models.CharField(default='ACTIVO', max_length=25)),
                ('valorUnidadElemento', models.IntegerField()),
                ('firmaDigital', models.ImageField(blank=True, null=True, upload_to='firmaDigital/')),
                ('observacionesPrestamo', models.TextField()),
                ('nombreEntrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_entregados', to=settings.AUTH_USER_MODEL)),
                ('nombreRecibe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('serialSenaElemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='UsuariosSena.InventarioDevolutivo')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
        migrations.AddField(
            model_name='inventariodevolutivo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsuariosSena.ProductosInventarioDevolutivo'),
        ),
        migrations.CreateModel(
            name='InventarioConsumible',
            fields=[
                ('fechaAdquisicion', models.DateField(auto_now_add=True)),
                ('cantidadElemento', models.IntegerField()),
                ('costoTotalElemento', models.IntegerField(blank=True, null=True)),
                ('observacionElemento', models.CharField(max_length=25)),
                ('facturaElemento', models.ImageField(blank=True, null=True, upload_to='facturaElemento/')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('productoConsumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsuariosSena.ProductosInventarioConsumible')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaConsumible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('cantidad_prestada', models.PositiveIntegerField()),
                ('observaciones_prestamo', models.TextField()),
                ('firmaDigital', models.ImageField(blank=True, null=True, upload_to='firmaDigital/')),
                ('idC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='UsuariosSena.InventarioConsumible')),
                ('nombre_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('responsable_Entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
