# Generated by Django 4.2.6 on 2023-11-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestamo",
            name="estado",
            field=models.CharField(default="ACTIVO", max_length=10),
        ),
    ]
