# Generated by Django 4.2.6 on 2023-11-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0002_prestamo_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementosConsumible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaAdquisicion", models.DateField(auto_now_add=True)),
                ("nombreElemento", models.CharField(max_length=25)),
                (
                    "categoriaElemento",
                    models.CharField(
                        choices=[("D", "Devolutivo"), ("C", "Consumible")],
                        default="C",
                        max_length=25,
                    ),
                ),
                (
                    "estadoElemento",
                    models.CharField(
                        choices=[("D", "Disponible"), ("A", "Agotado")],
                        default="D",
                        max_length=25,
                    ),
                ),
                ("descripcionElemento", models.CharField(max_length=25)),
                ("observacionElemento", models.CharField(max_length=25)),
                ("cantidadElemento", models.IntegerField()),
                ("costoUnidadElemento", models.IntegerField()),
                ("costoTotalElemento", models.IntegerField(blank=True, null=True)),
                ("lote", models.CharField(max_length=25)),
                (
                    "facturaElemento",
                    models.ImageField(
                        blank=True, null=True, upload_to="facturaElemento/"
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Elementos",
            new_name="ElementosDevolutivo",
        ),
        migrations.RenameModel(
            old_name="PrestamoConsumible",
            new_name="EntregaConsumible",
        ),
    ]
